pipeline:
  projectIdentifier: Cloud_Architecture
  orgIdentifier: EA
  tags: {}
  stages:
    - stage:
        name: IAC-Web-App-Destroy
        identifier: IACec2
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformPlan
                  name: IAC-Web-App-Destroy
                  identifier: IACWebApp
                  spec:
                    provisionerIdentifier: ec2_plan_id
                    configuration:
                      command: Destroy
                      configFiles:
                        store:
                          spec:
                            connectorRef: org.RKRepo
                            gitFetchType: Branch
                            branch: feature-01
                            folderPath: patterns/lab/ec2-asg
                          type: Github
                      secretManagerRef: harnessSecretManager
                      skipRefreshCommand: false
                    delegateSelectors:
                      - custom-tf-delegate
                  timeout: 10m
                  strategy:
                    parallelism: 1
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
              - step:
                  type: TerraformDestroy
                  name: IAC-Web-App-Destroy
                  identifier: IACWebAppDestroy
                  spec:
                    provisionerIdentifier: ec2_plan_id
                    configuration:
                      type: InheritFromPlan
                    delegateSelectors:
                      - custom-tf-delegate
                  timeout: 10m
                  when:
                    stageStatus: Success
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: MarkAsFailure
        tags: {}
        delegateSelectors:
          - eagl-awslab-terraform-delegate
        strategy:
          parallelism: 1
        when:
          pipelineStatus: All
  identifier: IACWebApp_Destroy
  name: IAC-Web-App - Destroy
