apiVersion: v1
kind: Service
metadata:
  name: student-app-svc
  labels:
    app: studentapp
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: studentapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-studentapp
  labels:
    app: studentapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studentapp
  template:
    metadata:
      labels:
        app: studentapp
    spec:
      containers:
      - name: studentapp
        image: studentapp:sppring-boot-webapp
        ports:
        - containerPort: 8080